-- ============================================================
-- PANINI WC2026 — Seed Data
-- Run AFTER schema.sql
-- ============================================================

-- Teams
INSERT INTO panini.teams (code, name, "group") VALUES
  ('FWC', 'World Cup Intro', ''),
  ('ALG', 'Algeria', 'J'),
  ('ARG', 'Argentina', 'J'),
  ('AUS', 'Australia', 'D'),
  ('AUT', 'Austria', 'J'),
  ('BEL', 'Belgium', 'G'),
  ('BIH', 'Bosnia & Herz.', 'B'),
  ('BRA', 'Brazil', 'C'),
  ('CAN', 'Canada', 'B'),
  ('CPV', 'Cape Verde', 'H'),
  ('COL', 'Colombia', 'K'),
  ('COD', 'DR Congo', 'K'),
  ('CRO', 'Croatia', 'L'),
  ('CUW', 'Curaçao', 'E'),
  ('CZE', 'Czechia', 'A'),
  ('ECU', 'Ecuador', 'E'),
  ('EGY', 'Egypt', 'G'),
  ('ENG', 'England', 'L'),
  ('FRA', 'France', 'I'),
  ('GER', 'Germany', 'E'),
  ('GHA', 'Ghana', 'L'),
  ('HAI', 'Haiti', 'C'),
  ('IRN', 'Iran', 'G'),
  ('IRQ', 'Iraq', 'I'),
  ('CIV', 'Ivory Coast', 'E'),
  ('JPN', 'Japan', 'F'),
  ('JOR', 'Jordan', 'J'),
  ('MEX', 'Mexico', 'A'),
  ('MAR', 'Morocco', 'C'),
  ('NED', 'Netherlands', 'F'),
  ('NZL', 'New Zealand', 'G'),
  ('NOR', 'Norway', 'I'),
  ('PAN', 'Panama', 'L'),
  ('PAR', 'Paraguay', 'D'),
  ('POR', 'Portugal', 'K'),
  ('QAT', 'Qatar', 'B'),
  ('KSA', 'Saudi Arabia', 'H'),
  ('SCO', 'Scotland', 'C'),
  ('SEN', 'Senegal', 'I'),
  ('RSA', 'South Africa', 'A'),
  ('KOR', 'South Korea', 'A'),
  ('ESP', 'Spain', 'H'),
  ('SWE', 'Sweden', 'F'),
  ('SUI', 'Switzerland', 'B'),
  ('TUN', 'Tunisia', 'F'),
  ('TUR', 'Türkiye', 'D'),
  ('URU', 'Uruguay', 'H'),
  ('USA', 'USA', 'D'),
  ('UZB', 'Uzbekistan', 'K');

-- Stickers (980 total)
INSERT INTO panini.stickers (id, team_code, number, description, is_foil, sticker_type) VALUES
  ('FWC0', 'FWC', 0, 'Panini Logo', true, 'standard'),
  ('FWC1', 'FWC', 1, 'Official Emblem', true, 'standard'),
  ('FWC2', 'FWC', 2, 'Official Emblem', true, 'standard'),
  ('FWC3', 'FWC', 3, 'Official Mascots', true, 'standard'),
  ('FWC4', 'FWC', 4, 'Official Slogan', true, 'standard'),
  ('FWC5', 'FWC', 5, 'Official Ball', true, 'standard'),
  ('FWC6', 'FWC', 6, 'Canada', true, 'standard'),
  ('FWC7', 'FWC', 7, 'Mexico', true, 'standard'),
  ('FWC8', 'FWC', 8, 'USA', true, 'standard'),
  ('FWC9', 'FWC', 9, 'Italy 1934', true, 'standard'),
  ('FWC10', 'FWC', 10, 'Uruguay 1950', true, 'standard'),
  ('FWC11', 'FWC', 11, 'West Germany 1954', true, 'standard'),
  ('FWC12', 'FWC', 12, 'Brazil 1962', true, 'standard'),
  ('FWC13', 'FWC', 13, 'West Germany 1974', true, 'standard'),
  ('FWC14', 'FWC', 14, 'Argentina 1986', true, 'standard'),
  ('FWC15', 'FWC', 15, 'Brazil 1994', true, 'standard'),
  ('FWC16', 'FWC', 16, 'Brazil 2002', true, 'standard'),
  ('FWC17', 'FWC', 17, 'Italy 2006', true, 'standard'),
  ('FWC18', 'FWC', 18, 'Germany 2014', true, 'standard'),
  ('FWC19', 'FWC', 19, 'Argentina 2022', true, 'standard'),
  ('ALG1', 'ALG', 1, 'Team Logo', true, 'standard'),
  ('ALG2', 'ALG', 2, 'Alexis Guendouz', false, 'standard'),
  ('ALG3', 'ALG', 3, 'Ramy Bensebaini', false, 'standard'),
  ('ALG4', 'ALG', 4, 'Youcef Atal', false, 'standard'),
  ('ALG5', 'ALG', 5, 'Rayan Aït', false, 'standard'),
  ('ALG6', 'ALG', 6, 'Mohamed Amine Tougai', false, 'standard'),
  ('ALG7', 'ALG', 7, 'Aïssa Mandi', false, 'standard'),
  ('ALG8', 'ALG', 8, 'Ismael Bennacer', false, 'standard'),
  ('ALG9', 'ALG', 9, 'Houssem Aquar', false, 'standard'),
  ('ALG10', 'ALG', 10, 'Hicham Boudaoui', false, 'standard'),
  ('ALG11', 'ALG', 11, 'Ramiz Zerrouki', false, 'standard'),
  ('ALG12', 'ALG', 12, 'Nabil Bentalab', false, 'standard'),
  ('ALG13', 'ALG', 13, 'Team Photo', false, 'standard'),
  ('ALG14', 'ALG', 14, 'Farès Chaibi', false, 'standard'),
  ('ALG15', 'ALG', 15, 'Riyad Mahrez', false, 'standard'),
  ('ALG16', 'ALG', 16, 'Said Benrahma', false, 'standard'),
  ('ALG17', 'ALG', 17, 'Anis Hadj Moussa', false, 'standard'),
  ('ALG18', 'ALG', 18, 'Amine Gouiri', false, 'standard'),
  ('ALG19', 'ALG', 19, 'Baghdad Bounedjah', false, 'standard'),
  ('ALG20', 'ALG', 20, 'Mohammed Amoura', false, 'standard'),
  ('ARG1', 'ARG', 1, 'Team Logo', true, 'standard'),
  ('ARG2', 'ARG', 2, 'Emiliano Martinez', false, 'standard'),
  ('ARG3', 'ARG', 3, 'Nahuel Molina', false, 'standard'),
  ('ARG4', 'ARG', 4, 'Cristian Romero', false, 'standard'),
  ('ARG5', 'ARG', 5, 'Nicolas Otamendi', false, 'standard'),
  ('ARG6', 'ARG', 6, 'Nicolas Tagliafico', false, 'standard'),
  ('ARG7', 'ARG', 7, 'Leonardo Balerdi', false, 'standard'),
  ('ARG8', 'ARG', 8, 'Enzo Fernandez', false, 'standard'),
  ('ARG9', 'ARG', 9, 'Alexis Mac Allister', false, 'standard'),
  ('ARG10', 'ARG', 10, 'Rodrigo De Paul', false, 'standard'),
  ('ARG11', 'ARG', 11, 'Exequiel Palacios', false, 'standard'),
  ('ARG12', 'ARG', 12, 'Leandro Paredes', false, 'standard'),
  ('ARG13', 'ARG', 13, 'Team Photo', false, 'standard'),
  ('ARG14', 'ARG', 14, 'Nico Paz', false, 'standard'),
  ('ARG15', 'ARG', 15, 'Franco Mastantuono', false, 'standard'),
  ('ARG16', 'ARG', 16, 'Nico Gonzalez', false, 'standard'),
  ('ARG17', 'ARG', 17, 'Lionel Messi', false, 'standard'),
  ('ARG18', 'ARG', 18, 'Lautaro Martinez', false, 'standard'),
  ('ARG19', 'ARG', 19, 'Julian Alvarez', false, 'standard'),
  ('ARG20', 'ARG', 20, 'Giuliano Simeone', false, 'standard'),
  ('AUS1', 'AUS', 1, 'Team Logo', true, 'standard'),
  ('AUS2', 'AUS', 2, 'Mathew Ryan', false, 'standard'),
  ('AUS3', 'AUS', 3, 'Joe Gauci', false, 'standard'),
  ('AUS4', 'AUS', 4, 'Harry Souttar', false, 'standard'),
  ('AUS5', 'AUS', 5, 'Alessandro Circati', false, 'standard'),
  ('AUS6', 'AUS', 6, 'Jordan Bos', false, 'standard'),
  ('AUS7', 'AUS', 7, 'Aziz Behich', false, 'standard'),
  ('AUS8', 'AUS', 8, 'Cameron Burgess', false, 'standard'),
  ('AUS9', 'AUS', 9, 'Lewis Miller', false, 'standard'),
  ('AUS10', 'AUS', 10, 'Milos Degenek', false, 'standard'),
  ('AUS11', 'AUS', 11, 'Jackson Irvine', false, 'standard'),
  ('AUS12', 'AUS', 12, 'Riley McGree', false, 'standard'),
  ('AUS13', 'AUS', 13, 'Team Photo', false, 'standard'),
  ('AUS14', 'AUS', 14, 'Aiden O''Neill', false, 'standard'),
  ('AUS15', 'AUS', 15, 'Connor Metcalfe', false, 'standard'),
  ('AUS16', 'AUS', 16, 'Patrick Yazbek', false, 'standard'),
  ('AUS17', 'AUS', 17, 'Craig Goodwin', false, 'standard'),
  ('AUS18', 'AUS', 18, 'Kusini Vengi', false, 'standard'),
  ('AUS19', 'AUS', 19, 'Nestory Irankunda', false, 'standard'),
  ('AUS20', 'AUS', 20, 'Mohamed Touré', false, 'standard'),
  ('AUT1', 'AUT', 1, 'Team Logo', true, 'standard'),
  ('AUT2', 'AUT', 2, 'Alexander Schlager', false, 'standard'),
  ('AUT3', 'AUT', 3, 'Patrick Pentz', false, 'standard'),
  ('AUT4', 'AUT', 4, 'David Alaba', false, 'standard'),
  ('AUT5', 'AUT', 5, 'Kevin Danso', false, 'standard'),
  ('AUT6', 'AUT', 6, 'Philipp Lienhart', false, 'standard'),
  ('AUT7', 'AUT', 7, 'Stefan Posch', false, 'standard'),
  ('AUT8', 'AUT', 8, 'Phillipp Mwene', false, 'standard'),
  ('AUT9', 'AUT', 9, 'Alexander Prass', false, 'standard'),
  ('AUT10', 'AUT', 10, 'Xaver Schlager', false, 'standard'),
  ('AUT11', 'AUT', 11, 'Marcel Sabitzer', false, 'standard'),
  ('AUT12', 'AUT', 12, 'Konrad Laimer', false, 'standard'),
  ('AUT13', 'AUT', 13, 'Team Photo', false, 'standard'),
  ('AUT14', 'AUT', 14, 'Florian Grillitsch', false, 'standard'),
  ('AUT15', 'AUT', 15, 'Nicolas Seiwald', false, 'standard'),
  ('AUT16', 'AUT', 16, 'Romano Schmid', false, 'standard'),
  ('AUT17', 'AUT', 17, 'Patrick Wimmer', false, 'standard'),
  ('AUT18', 'AUT', 18, 'Christoph Baumgartner', false, 'standard'),
  ('AUT19', 'AUT', 19, 'Michael Gregoritsch', false, 'standard'),
  ('AUT20', 'AUT', 20, 'Marko Arnautović', false, 'standard'),
  ('BEL1', 'BEL', 1, 'Team Logo', true, 'standard'),
  ('BEL2', 'BEL', 2, 'Thibaut Courtois', false, 'standard'),
  ('BEL3', 'BEL', 3, 'Arthur Theate', false, 'standard'),
  ('BEL4', 'BEL', 4, 'Timothy Castagne', false, 'standard'),
  ('BEL5', 'BEL', 5, 'Zeno Debast', false, 'standard'),
  ('BEL6', 'BEL', 6, 'Brandon Mechele', false, 'standard'),
  ('BEL7', 'BEL', 7, 'Maxim De Cuyper', false, 'standard'),
  ('BEL8', 'BEL', 8, 'Thomas Meunier', false, 'standard'),
  ('BEL9', 'BEL', 9, 'Youri Tielemans', false, 'standard'),
  ('BEL10', 'BEL', 10, 'Amadou Onana', false, 'standard'),
  ('BEL11', 'BEL', 11, 'Nicolas Raskin', false, 'standard'),
  ('BEL12', 'BEL', 12, 'Alexis Saelemaekers', false, 'standard'),
  ('BEL13', 'BEL', 13, 'Team Photo', false, 'standard'),
  ('BEL14', 'BEL', 14, 'Hans Vanaken', false, 'standard'),
  ('BEL15', 'BEL', 15, 'Kevin De Bruyne', false, 'standard'),
  ('BEL16', 'BEL', 16, 'Jérémy Doku', false, 'standard'),
  ('BEL17', 'BEL', 17, 'Charles De Ketelaere', false, 'standard'),
  ('BEL18', 'BEL', 18, 'Leandro Trossard', false, 'standard'),
  ('BEL19', 'BEL', 19, 'Loïs Openda', false, 'standard'),
  ('BEL20', 'BEL', 20, 'Romelu Lukaku', false, 'standard'),
  ('BIH1', 'BIH', 1, 'Team Logo', true, 'standard'),
  ('BIH2', 'BIH', 2, 'Nikola Vasilj', false, 'standard'),
  ('BIH3', 'BIH', 3, 'Amer Dedic', false, 'standard'),
  ('BIH4', 'BIH', 4, 'Sead Kolasinac', false, 'standard'),
  ('BIH5', 'BIH', 5, 'Tarik Muharemovic', false, 'standard'),
  ('BIH6', 'BIH', 6, 'Nihad Mujakic', false, 'standard'),
  ('BIH7', 'BIH', 7, 'Nikola Katic', false, 'standard'),
  ('BIH8', 'BIH', 8, 'Amir Hadziahmetovic', false, 'standard'),
  ('BIH9', 'BIH', 9, 'Benjamin Tahirovic', false, 'standard'),
  ('BIH10', 'BIH', 10, 'Armin Gigovic', false, 'standard'),
  ('BIH11', 'BIH', 11, 'Ivan Sunjic', false, 'standard'),
  ('BIH12', 'BIH', 12, 'Ivan Basic', false, 'standard'),
  ('BIH13', 'BIH', 13, 'Team Photo', false, 'standard'),
  ('BIH14', 'BIH', 14, 'Dzenis Burnic', false, 'standard'),
  ('BIH15', 'BIH', 15, 'Esmir Bajraktarevic', false, 'standard'),
  ('BIH16', 'BIH', 16, 'Amar Memic', false, 'standard'),
  ('BIH17', 'BIH', 17, 'Ermedin Demirovic', false, 'standard'),
  ('BIH18', 'BIH', 18, 'Edin Dzeko', false, 'standard'),
  ('BIH19', 'BIH', 19, 'Samed Bazdar', false, 'standard'),
  ('BIH20', 'BIH', 20, 'Haris Tabakovic', false, 'standard'),
  ('BRA1', 'BRA', 1, 'Team Logo', true, 'standard'),
  ('BRA2', 'BRA', 2, 'Alisson', false, 'standard'),
  ('BRA3', 'BRA', 3, 'Bento', false, 'standard'),
  ('BRA4', 'BRA', 4, 'Marquinhos', false, 'standard'),
  ('BRA5', 'BRA', 5, 'Éder Militão', false, 'standard'),
  ('BRA6', 'BRA', 6, 'Gabriel Magalhães', false, 'standard'),
  ('BRA7', 'BRA', 7, 'Danilo', false, 'standard'),
  ('BRA8', 'BRA', 8, 'Wesley', false, 'standard'),
  ('BRA9', 'BRA', 9, 'Lucas Paquetá', false, 'standard'),
  ('BRA10', 'BRA', 10, 'Casemiro', false, 'standard'),
  ('BRA11', 'BRA', 11, 'Bruno Guimarães', false, 'standard'),
  ('BRA12', 'BRA', 12, 'Luiz Henrique', false, 'standard'),
  ('BRA13', 'BRA', 13, 'Team Photo', false, 'standard'),
  ('BRA14', 'BRA', 14, 'Vinicius Júnior', false, 'standard'),
  ('BRA15', 'BRA', 15, 'Rodrygo', false, 'standard'),
  ('BRA16', 'BRA', 16, 'João Pedro', false, 'standard'),
  ('BRA17', 'BRA', 17, 'Matheus Cunha', false, 'standard'),
  ('BRA18', 'BRA', 18, 'Gabriel Martinelli', false, 'standard'),
  ('BRA19', 'BRA', 19, 'Raphinha', false, 'standard'),
  ('BRA20', 'BRA', 20, 'Estêvão', false, 'standard'),
  ('CAN1', 'CAN', 1, 'Team Logo', true, 'standard'),
  ('CAN2', 'CAN', 2, 'Dayne St.Clair', false, 'standard'),
  ('CAN3', 'CAN', 3, 'Alphonso Davies', false, 'standard'),
  ('CAN4', 'CAN', 4, 'Alistair Johnston', false, 'standard'),
  ('CAN5', 'CAN', 5, 'Samuel Adekugbe', false, 'standard'),
  ('CAN6', 'CAN', 6, 'Riche Larvea', false, 'standard'),
  ('CAN7', 'CAN', 7, 'Derek Cornelius', false, 'standard'),
  ('CAN8', 'CAN', 8, 'Moïse Bombito', false, 'standard'),
  ('CAN9', 'CAN', 9, 'Kamal Miller', false, 'standard'),
  ('CAN10', 'CAN', 10, 'Stephen Eustáquio', false, 'standard'),
  ('CAN11', 'CAN', 11, 'Ismaël Koné', false, 'standard'),
  ('CAN12', 'CAN', 12, 'Jonathan Osorio', false, 'standard'),
  ('CAN13', 'CAN', 13, 'Team Photo', false, 'standard'),
  ('CAN14', 'CAN', 14, 'Jacob Shaffelburg', false, 'standard'),
  ('CAN15', 'CAN', 15, 'Mathieu Choinière', false, 'standard'),
  ('CAN16', 'CAN', 16, 'Niko Sigur', false, 'standard'),
  ('CAN17', 'CAN', 17, 'Tajon Buchanan', false, 'standard'),
  ('CAN18', 'CAN', 18, 'Liam Millar', false, 'standard'),
  ('CAN19', 'CAN', 19, 'Cyle Larin', false, 'standard'),
  ('CAN20', 'CAN', 20, 'Jonathan David', false, 'standard'),
  ('CPV1', 'CPV', 1, 'Team Logo', true, 'standard'),
  ('CPV2', 'CPV', 2, 'Vozinha', false, 'standard'),
  ('CPV3', 'CPV', 3, 'Logan Costa', false, 'standard'),
  ('CPV4', 'CPV', 4, 'Pico', false, 'standard'),
  ('CPV5', 'CPV', 5, 'Diney', false, 'standard'),
  ('CPV6', 'CPV', 6, 'Steven Moreira', false, 'standard'),
  ('CPV7', 'CPV', 7, 'Wagner Pina', false, 'standard'),
  ('CPV8', 'CPV', 8, 'Joao Paulo', false, 'standard'),
  ('CPV9', 'CPV', 9, 'Yannick Semedo', false, 'standard'),
  ('CPV10', 'CPV', 10, 'Kevin Pina', false, 'standard'),
  ('CPV11', 'CPV', 11, 'Patrick Andrade', false, 'standard'),
  ('CPV12', 'CPV', 12, 'Jamiro Monteiro', false, 'standard'),
  ('CPV13', 'CPV', 13, 'Team Photo', false, 'standard'),
  ('CPV14', 'CPV', 14, 'Deroy Duarte', false, 'standard'),
  ('CPV15', 'CPV', 15, 'Garry Rodrigues', false, 'standard'),
  ('CPV16', 'CPV', 16, 'Jovane Cabral', false, 'standard'),
  ('CPV17', 'CPV', 17, 'Ryan Mendes', false, 'standard'),
  ('CPV18', 'CPV', 18, 'Dailon Livramento', false, 'standard'),
  ('CPV19', 'CPV', 19, 'Willy Semedo', false, 'standard'),
  ('CPV20', 'CPV', 20, 'Bebe', false, 'standard'),
  ('COL1', 'COL', 1, 'Team Logo', true, 'standard'),
  ('COL2', 'COL', 2, 'Camilo Vargas', false, 'standard'),
  ('COL3', 'COL', 3, 'David Ospina', false, 'standard'),
  ('COL4', 'COL', 4, 'Dávinson Sánchez', false, 'standard'),
  ('COL5', 'COL', 5, 'Yerry Mina', false, 'standard'),
  ('COL6', 'COL', 6, 'Daniel Munoz', false, 'standard'),
  ('COL7', 'COL', 7, 'Johan Mojica', false, 'standard'),
  ('COL8', 'COL', 8, 'Jhon Lucumí', false, 'standard'),
  ('COL9', 'COL', 9, 'Santiago Arias', false, 'standard'),
  ('COL10', 'COL', 10, 'Jefferson Lerma', false, 'standard'),
  ('COL11', 'COL', 11, 'Kevin Castaño', false, 'standard'),
  ('COL12', 'COL', 12, 'Richard Rios', false, 'standard'),
  ('COL13', 'COL', 13, 'Team Photo', false, 'standard'),
  ('COL14', 'COL', 14, 'James Rodriguez', false, 'standard'),
  ('COL15', 'COL', 15, 'Juan Fernando Quintero', false, 'standard'),
  ('COL16', 'COL', 16, 'Jorge Carrascal', false, 'standard'),
  ('COL17', 'COL', 17, 'Jon Arias', false, 'standard'),
  ('COL18', 'COL', 18, 'Jhon Cordova', false, 'standard'),
  ('COL19', 'COL', 19, 'Luis Suarez', false, 'standard'),
  ('COL20', 'COL', 20, 'Luis Diaz', false, 'standard'),
  ('COD1', 'COD', 1, 'Team Logo', true, 'standard'),
  ('COD2', 'COD', 2, 'Lionel Mpasi', false, 'standard'),
  ('COD3', 'COD', 3, 'Aaron Wan', false, 'standard'),
  ('COD4', 'COD', 4, 'Axel Tuanzebe', false, 'standard'),
  ('COD5', 'COD', 5, 'Arthur Masuaku', false, 'standard'),
  ('COD6', 'COD', 6, 'Chancel Mbemba', false, 'standard'),
  ('COD7', 'COD', 7, 'Joris Kayembe', false, 'standard'),
  ('COD8', 'COD', 8, 'Charles Pickel', false, 'standard'),
  ('COD9', 'COD', 9, 'Ngal''ayel Mukau', false, 'standard'),
  ('COD10', 'COD', 10, 'Edo Kayembe', false, 'standard'),
  ('COD11', 'COD', 11, 'Samuel Moutoussamy', false, 'standard'),
  ('COD12', 'COD', 12, 'Noah Sadiki', false, 'standard'),
  ('COD13', 'COD', 13, 'Team Photo', false, 'standard'),
  ('COD14', 'COD', 14, 'Théo Bongonda', false, 'standard'),
  ('COD15', 'COD', 15, 'Meschak Elia', false, 'standard'),
  ('COD16', 'COD', 16, 'Yoane Wissa', false, 'standard'),
  ('COD17', 'COD', 17, 'Brian Cipenga', false, 'standard'),
  ('COD18', 'COD', 18, 'Fiston Mayele', false, 'standard'),
  ('COD19', 'COD', 19, 'Cédric Bakambu', false, 'standard'),
  ('COD20', 'COD', 20, 'Nathanaël Mbuku', false, 'standard'),
  ('CRO1', 'CRO', 1, 'Team Logo', true, 'standard'),
  ('CRO2', 'CRO', 2, 'Dominik Livaković', false, 'standard'),
  ('CRO3', 'CRO', 3, 'Duje Caleta', false, 'standard'),
  ('CRO4', 'CRO', 4, 'Josko Gvardiol', false, 'standard'),
  ('CRO5', 'CRO', 5, 'Josip Stanišić', false, 'standard'),
  ('CRO6', 'CRO', 6, 'Luka Vušković', false, 'standard'),
  ('CRO7', 'CRO', 7, 'Josip Sutalo', false, 'standard'),
  ('CRO8', 'CRO', 8, 'Kristijan Jakic', false, 'standard'),
  ('CRO9', 'CRO', 9, 'Luka Modrić', false, 'standard'),
  ('CRO10', 'CRO', 10, 'Mateo Kovacic', false, 'standard'),
  ('CRO11', 'CRO', 11, 'Martin Baturina', false, 'standard'),
  ('CRO12', 'CRO', 12, 'Lovro Majer', false, 'standard'),
  ('CRO13', 'CRO', 13, 'Team Photo', false, 'standard'),
  ('CRO14', 'CRO', 14, 'Mario Pasalic', false, 'standard'),
  ('CRO15', 'CRO', 15, 'Petar Sucic', false, 'standard'),
  ('CRO16', 'CRO', 16, 'Ivan Perišić', false, 'standard'),
  ('CRO17', 'CRO', 17, 'Marco Pasalic', false, 'standard'),
  ('CRO18', 'CRO', 18, 'Ante Budimir', false, 'standard'),
  ('CRO19', 'CRO', 19, 'Andrej Kramarić', false, 'standard'),
  ('CRO20', 'CRO', 20, 'Franjo Ivanovic', false, 'standard'),
  ('CUW1', 'CUW', 1, 'Team Logo', true, 'standard'),
  ('CUW2', 'CUW', 2, 'Eloy Room', false, 'standard'),
  ('CUW3', 'CUW', 3, 'Armando Obispo', false, 'standard'),
  ('CUW4', 'CUW', 4, 'Sherel Floranus', false, 'standard'),
  ('CUW5', 'CUW', 5, 'Jurien Gaari', false, 'standard'),
  ('CUW6', 'CUW', 6, 'Joshua Brenet', false, 'standard'),
  ('CUW7', 'CUW', 7, 'Roshon Van Eijma', false, 'standard'),
  ('CUW8', 'CUW', 8, 'Shurandy Sambo', false, 'standard'),
  ('CUW9', 'CUW', 9, 'Livano Comenencia', false, 'standard'),
  ('CUW10', 'CUW', 10, 'Godfried Roemeratoe', false, 'standard'),
  ('CUW11', 'CUW', 11, 'Juninho Bacuna', false, 'standard'),
  ('CUW12', 'CUW', 12, 'Leandro Bacuna', false, 'standard'),
  ('CUW13', 'CUW', 13, 'Team Photo', false, 'standard'),
  ('CUW14', 'CUW', 14, 'Tahith Chong', false, 'standard'),
  ('CUW15', 'CUW', 15, 'Kenji Gorre', false, 'standard'),
  ('CUW16', 'CUW', 16, 'Jearl Margaritha', false, 'standard'),
  ('CUW17', 'CUW', 17, 'Jurgen Locadia', false, 'standard'),
  ('CUW18', 'CUW', 18, 'Jeremy Antonisse', false, 'standard'),
  ('CUW19', 'CUW', 19, 'Gervane Kastaneer', false, 'standard'),
  ('CUW20', 'CUW', 20, 'Sontje Hansen', false, 'standard'),
  ('CZE1', 'CZE', 1, 'Team Logo', true, 'standard'),
  ('CZE2', 'CZE', 2, 'Matej Kovar', false, 'standard'),
  ('CZE3', 'CZE', 3, 'Jindrich Stanek', false, 'standard'),
  ('CZE4', 'CZE', 4, 'Ladislav Krejci', false, 'standard'),
  ('CZE5', 'CZE', 5, 'Vladimir Coufal', false, 'standard'),
  ('CZE6', 'CZE', 6, 'Jaroslav Zeleny', false, 'standard'),
  ('CZE7', 'CZE', 7, 'Tomas Holes', false, 'standard'),
  ('CZE8', 'CZE', 8, 'David Zima', false, 'standard'),
  ('CZE9', 'CZE', 9, 'Michal Sadilek', false, 'standard'),
  ('CZE10', 'CZE', 10, 'Lukas Provod', false, 'standard'),
  ('CZE11', 'CZE', 11, 'Lukas Cerv', false, 'standard'),
  ('CZE12', 'CZE', 12, 'Tomas Soucek', false, 'standard'),
  ('CZE13', 'CZE', 13, 'Team Photo', false, 'standard'),
  ('CZE14', 'CZE', 14, 'Pavel Sulc', false, 'standard'),
  ('CZE15', 'CZE', 15, 'Matej Vydra', false, 'standard'),
  ('CZE16', 'CZE', 16, 'Vasil Kusej', false, 'standard'),
  ('CZE17', 'CZE', 17, 'Tomas Chory', false, 'standard'),
  ('CZE18', 'CZE', 18, 'Vaclav Cerny', false, 'standard'),
  ('CZE19', 'CZE', 19, 'Adam Hlozek', false, 'standard'),
  ('CZE20', 'CZE', 20, 'Patrik Schick', false, 'standard'),
  ('ECU1', 'ECU', 1, 'Team Logo', true, 'standard'),
  ('ECU2', 'ECU', 2, 'Hernán Galíndez', false, 'standard'),
  ('ECU3', 'ECU', 3, 'Gonzalo Valle', false, 'standard'),
  ('ECU4', 'ECU', 4, 'Piero Hincapié', false, 'standard'),
  ('ECU5', 'ECU', 5, 'Pervis Estupiñán', false, 'standard'),
  ('ECU6', 'ECU', 6, 'Willian Pacho', false, 'standard'),
  ('ECU7', 'ECU', 7, 'Ángelo Preciado', false, 'standard'),
  ('ECU8', 'ECU', 8, 'Joel Ordóñez', false, 'standard'),
  ('ECU9', 'ECU', 9, 'Moises Caicedo', false, 'standard'),
  ('ECU10', 'ECU', 10, 'Alan Franco', false, 'standard'),
  ('ECU11', 'ECU', 11, 'Kendry Paez', false, 'standard'),
  ('ECU12', 'ECU', 12, 'Pedro Vite', false, 'standard'),
  ('ECU13', 'ECU', 13, 'Team Photo', false, 'standard'),
  ('ECU14', 'ECU', 14, 'John Yeboah', false, 'standard'),
  ('ECU15', 'ECU', 15, 'Leonardo Campana', false, 'standard'),
  ('ECU16', 'ECU', 16, 'Gonzalo Plata', false, 'standard'),
  ('ECU17', 'ECU', 17, 'Nilson Angulo', false, 'standard'),
  ('ECU18', 'ECU', 18, 'Alan Minda', false, 'standard'),
  ('ECU19', 'ECU', 19, 'Kevin Rodriguez', false, 'standard'),
  ('ECU20', 'ECU', 20, 'Enner Valencia', false, 'standard'),
  ('EGY1', 'EGY', 1, 'Team Logo', true, 'standard'),
  ('EGY2', 'EGY', 2, 'Mohamed El Shenawy', false, 'standard'),
  ('EGY3', 'EGY', 3, 'Mohamed Hany', false, 'standard'),
  ('EGY4', 'EGY', 4, 'Mohamed Hamdy', false, 'standard'),
  ('EGY5', 'EGY', 5, 'Yasser Ibrahim', false, 'standard'),
  ('EGY6', 'EGY', 6, 'Khaled Sobhi', false, 'standard'),
  ('EGY7', 'EGY', 7, 'Ramy Rabia', false, 'standard'),
  ('EGY8', 'EGY', 8, 'Hossam Abdelmaguid', false, 'standard'),
  ('EGY9', 'EGY', 9, 'Ahmed Fatouh', false, 'standard'),
  ('EGY10', 'EGY', 10, 'Marwan Attia', false, 'standard'),
  ('EGY11', 'EGY', 11, 'Zizo', false, 'standard'),
  ('EGY12', 'EGY', 12, 'Hamdy Fathy', false, 'standard'),
  ('EGY13', 'EGY', 13, 'Team Photo', false, 'standard'),
  ('EGY14', 'EGY', 14, 'Mohamed Lasheen', false, 'standard'),
  ('EGY15', 'EGY', 15, 'Emam Ashour', false, 'standard'),
  ('EGY16', 'EGY', 16, 'Osama Faisal', false, 'standard'),
  ('EGY17', 'EGY', 17, 'Mohamed Salah', false, 'standard'),
  ('EGY18', 'EGY', 18, 'Mostafa Mohamed', false, 'standard'),
  ('EGY19', 'EGY', 19, 'Trezeguet', false, 'standard'),
  ('EGY20', 'EGY', 20, 'Omar Marmoush', false, 'standard'),
  ('ENG1', 'ENG', 1, 'Team Logo', true, 'standard'),
  ('ENG2', 'ENG', 2, 'Jordan Pickford', false, 'standard'),
  ('ENG3', 'ENG', 3, 'John Stones', false, 'standard'),
  ('ENG4', 'ENG', 4, 'Marc Guéhi', false, 'standard'),
  ('ENG5', 'ENG', 5, 'Ezri Konsa', false, 'standard'),
  ('ENG6', 'ENG', 6, 'Trent Alexander', false, 'standard'),
  ('ENG7', 'ENG', 7, 'Reece James', false, 'standard'),
  ('ENG8', 'ENG', 8, 'Dan Burn', false, 'standard'),
  ('ENG9', 'ENG', 9, 'Jordan Henderson', false, 'standard'),
  ('ENG10', 'ENG', 10, 'Declan Rice', false, 'standard'),
  ('ENG11', 'ENG', 11, 'Jude Bellingham', false, 'standard'),
  ('ENG12', 'ENG', 12, 'Cole Palmer', false, 'standard'),
  ('ENG13', 'ENG', 13, 'Team Photo', false, 'standard'),
  ('ENG14', 'ENG', 14, 'Morgan Rogers', false, 'standard'),
  ('ENG15', 'ENG', 15, 'Anthony Gordon', false, 'standard'),
  ('ENG16', 'ENG', 16, 'Phil Foden', false, 'standard'),
  ('ENG17', 'ENG', 17, 'Bukayo Saka', false, 'standard'),
  ('ENG18', 'ENG', 18, 'Harry Kane', false, 'standard'),
  ('ENG19', 'ENG', 19, 'Marcus Rashford', false, 'standard'),
  ('ENG20', 'ENG', 20, 'Ollie Watkins', false, 'standard'),
  ('FRA1', 'FRA', 1, 'Team Logo', true, 'standard'),
  ('FRA2', 'FRA', 2, 'Mike Maignan', false, 'standard'),
  ('FRA3', 'FRA', 3, 'Theo Hernandez', false, 'standard'),
  ('FRA4', 'FRA', 4, 'William Saliba', false, 'standard'),
  ('FRA5', 'FRA', 5, 'Jules Kounde', false, 'standard'),
  ('FRA6', 'FRA', 6, 'Ibrahima Konate', false, 'standard'),
  ('FRA7', 'FRA', 7, 'Dayot Upamecano', false, 'standard'),
  ('FRA8', 'FRA', 8, 'Lucas Digne', false, 'standard'),
  ('FRA9', 'FRA', 9, 'Aurélien Tchouaméni', false, 'standard'),
  ('FRA10', 'FRA', 10, 'Eduardo Camavinga', false, 'standard'),
  ('FRA11', 'FRA', 11, 'Manu Kone', false, 'standard'),
  ('FRA12', 'FRA', 12, 'Adrien Rabiot', false, 'standard'),
  ('FRA13', 'FRA', 13, 'Team Photo', false, 'standard'),
  ('FRA14', 'FRA', 14, 'Michael Olise', false, 'standard'),
  ('FRA15', 'FRA', 15, 'Ousmane Dembele', false, 'standard'),
  ('FRA16', 'FRA', 16, 'Bradley Barcola', false, 'standard'),
  ('FRA17', 'FRA', 17, 'Désiré Doué', false, 'standard'),
  ('FRA18', 'FRA', 18, 'Kingsley Coman', false, 'standard'),
  ('FRA19', 'FRA', 19, 'Hugo Ekitike', false, 'standard'),
  ('FRA20', 'FRA', 20, 'Kylian Mbappe', false, 'standard'),
  ('GER1', 'GER', 1, 'Team Logo', true, 'standard'),
  ('GER2', 'GER', 2, 'Marc Flekken', false, 'standard'),
  ('GER3', 'GER', 3, 'Jonathan Tah', false, 'standard'),
  ('GER4', 'GER', 4, 'David Raum', false, 'standard'),
  ('GER5', 'GER', 5, 'Nico Schlotterbeck', false, 'standard'),
  ('GER6', 'GER', 6, 'Antonio Rüdiger', false, 'standard'),
  ('GER7', 'GER', 7, 'Waldemar Anton', false, 'standard'),
  ('GER8', 'GER', 8, 'Ridle Baku', false, 'standard'),
  ('GER9', 'GER', 9, 'Maximilian Mittelstadt', false, 'standard'),
  ('GER10', 'GER', 10, 'Joshua Kimmich', false, 'standard'),
  ('GER11', 'GER', 11, 'Florian Wirtz', false, 'standard'),
  ('GER12', 'GER', 12, 'Felix Nmecha', false, 'standard'),
  ('GER13', 'GER', 13, 'Team Photo', false, 'standard'),
  ('GER14', 'GER', 14, 'Leon Goretzka', false, 'standard'),
  ('GER15', 'GER', 15, 'Jamal Musiala', false, 'standard'),
  ('GER16', 'GER', 16, 'Serge Gnabry', false, 'standard'),
  ('GER17', 'GER', 17, 'Kai Havertz', false, 'standard'),
  ('GER18', 'GER', 18, 'Leroy Sane', false, 'standard'),
  ('GER19', 'GER', 19, 'Karim Adeyemi', false, 'standard'),
  ('GER20', 'GER', 20, 'Nick Woltemade', false, 'standard'),
  ('GHA1', 'GHA', 1, 'Team Logo', true, 'standard'),
  ('GHA2', 'GHA', 2, 'Lawrence Ati Zigi', false, 'standard'),
  ('GHA3', 'GHA', 3, 'Tariq Lamptey', false, 'standard'),
  ('GHA4', 'GHA', 4, 'Mohammed Salisu', false, 'standard'),
  ('GHA5', 'GHA', 5, 'Alidu Seidu', false, 'standard'),
  ('GHA6', 'GHA', 6, 'Alexander Djiku', false, 'standard'),
  ('GHA7', 'GHA', 7, 'Gideon Mensah', false, 'standard'),
  ('GHA8', 'GHA', 8, 'Caleb Yirenkyi', false, 'standard'),
  ('GHA9', 'GHA', 9, 'Abdul Issahaku Fatawu', false, 'standard'),
  ('GHA10', 'GHA', 10, 'Thomas Partey', false, 'standard'),
  ('GHA11', 'GHA', 11, 'Salis Abdul Samed', false, 'standard'),
  ('GHA12', 'GHA', 12, 'Kamaldeen Sulemana', false, 'standard'),
  ('GHA13', 'GHA', 13, 'Team Photo', false, 'standard'),
  ('GHA14', 'GHA', 14, 'Mohammed Kudus', false, 'standard'),
  ('GHA15', 'GHA', 15, 'Inaki Williams', false, 'standard'),
  ('GHA16', 'GHA', 16, 'Jordan Ayew', false, 'standard'),
  ('GHA17', 'GHA', 17, 'Andrew Ayew', false, 'standard'),
  ('GHA18', 'GHA', 18, 'Joseph Paintsil', false, 'standard'),
  ('GHA19', 'GHA', 19, 'Osman Bukari', false, 'standard'),
  ('GHA20', 'GHA', 20, 'Antoine Semenyo', false, 'standard'),
  ('HAI1', 'HAI', 1, 'Team Logo', true, 'standard'),
  ('HAI2', 'HAI', 2, 'Johny Placide', false, 'standard'),
  ('HAI3', 'HAI', 3, 'Carlens Arcus', false, 'standard'),
  ('HAI4', 'HAI', 4, 'Martin Expérience', false, 'standard'),
  ('HAI5', 'HAI', 5, 'Jean-Baptiste', false, 'standard'),
  ('HAI6', 'HAI', 6, 'Ricardo Adé', false, 'standard'),
  ('HAI7', 'HAI', 7, 'Duke Lacroix', false, 'standard'),
  ('HAI8', 'HAI', 8, 'Garven Metusala', false, 'standard'),
  ('HAI9', 'HAI', 9, 'Hannes Delcroix', false, 'standard'),
  ('HAI10', 'HAI', 10, 'Leverton Pierre', false, 'standard'),
  ('HAI11', 'HAI', 11, 'Danley Jean Jacques', false, 'standard'),
  ('HAI12', 'HAI', 12, 'Jean-Phaël', false, 'standard'),
  ('HAI13', 'HAI', 13, 'Team Photo', false, 'standard'),
  ('HAI14', 'HAI', 14, 'Christopher Attys', false, 'standard'),
  ('HAI15', 'HAI', 15, 'Derrick Etienne Jr', false, 'standard'),
  ('HAI16', 'HAI', 16, 'Josue Casimir', false, 'standard'),
  ('HAI17', 'HAI', 17, 'Ruben Providence', false, 'standard'),
  ('HAI18', 'HAI', 18, 'Duckens Nazon', false, 'standard'),
  ('HAI19', 'HAI', 19, 'Louicius Deedson', false, 'standard'),
  ('HAI20', 'HAI', 20, 'Frantzdy Pierrot', false, 'standard'),
  ('IRN1', 'IRN', 1, 'Team Logo', true, 'standard'),
  ('IRN2', 'IRN', 2, 'Alireza Beiranvand', false, 'standard'),
  ('IRN3', 'IRN', 3, 'Morteza Pouraliganji', false, 'standard'),
  ('IRN4', 'IRN', 4, 'Ehsan Hajsafi', false, 'standard'),
  ('IRN5', 'IRN', 5, 'Milad Mohammadi', false, 'standard'),
  ('IRN6', 'IRN', 6, 'Shojae Khalilzadeh', false, 'standard'),
  ('IRN7', 'IRN', 7, 'Ramin Rezaeian', false, 'standard'),
  ('IRN8', 'IRN', 8, 'Hossein Kanaani', false, 'standard'),
  ('IRN9', 'IRN', 9, 'Sadegh Moharrami', false, 'standard'),
  ('IRN10', 'IRN', 10, 'Saleh Hardani', false, 'standard'),
  ('IRN11', 'IRN', 11, 'Saeed Ezatolahi', false, 'standard'),
  ('IRN12', 'IRN', 12, 'Saman Ghoddos', false, 'standard'),
  ('IRN13', 'IRN', 13, 'Team Photo', false, 'standard'),
  ('IRN14', 'IRN', 14, 'Omid Noorafkan', false, 'standard'),
  ('IRN15', 'IRN', 15, 'Roozbeh Cheshmi', false, 'standard'),
  ('IRN16', 'IRN', 16, 'Mohammad Mohebi', false, 'standard'),
  ('IRN17', 'IRN', 17, 'Sardar Azmoun', false, 'standard'),
  ('IRN18', 'IRN', 18, 'Mehdi Taremi', false, 'standard'),
  ('IRN19', 'IRN', 19, 'Alireza Jahanbakhsh', false, 'standard'),
  ('IRN20', 'IRN', 20, 'Ali Gholizadeh', false, 'standard'),
  ('IRQ1', 'IRQ', 1, 'Team Logo', true, 'standard'),
  ('IRQ2', 'IRQ', 2, 'Jalal Hassan', false, 'standard'),
  ('IRQ3', 'IRQ', 3, 'Rebin Sulaka', false, 'standard'),
  ('IRQ4', 'IRQ', 4, 'Hussein Ali', false, 'standard'),
  ('IRQ5', 'IRQ', 5, 'Akam Hashem', false, 'standard'),
  ('IRQ6', 'IRQ', 6, 'Merchas Doski', false, 'standard'),
  ('IRQ7', 'IRQ', 7, 'Zaid Tahseen', false, 'standard'),
  ('IRQ8', 'IRQ', 8, 'Manaf Younis', false, 'standard'),
  ('IRQ9', 'IRQ', 9, 'Zidane Iqbal', false, 'standard'),
  ('IRQ10', 'IRQ', 10, 'Amir Al-Ammari', false, 'standard'),
  ('IRQ11', 'IRQ', 11, 'Ibrahim Bavesh', false, 'standard'),
  ('IRQ12', 'IRQ', 12, 'Ali Jasim', false, 'standard'),
  ('IRQ13', 'IRQ', 13, 'Team Photo', false, 'standard'),
  ('IRQ14', 'IRQ', 14, 'Youssef Amyn', false, 'standard'),
  ('IRQ15', 'IRQ', 15, 'Aimar Sher', false, 'standard'),
  ('IRQ16', 'IRQ', 16, 'Marko Farji', false, 'standard'),
  ('IRQ17', 'IRQ', 17, 'Osama Rashid', false, 'standard'),
  ('IRQ18', 'IRQ', 18, 'Ali Al-Hamadi', false, 'standard'),
  ('IRQ19', 'IRQ', 19, 'Aymen Hussein', false, 'standard'),
  ('IRQ20', 'IRQ', 20, 'Mohanad Ali', false, 'standard'),
  ('CIV1', 'CIV', 1, 'Team Logo', true, 'standard'),
  ('CIV2', 'CIV', 2, 'Yahia Fofana', false, 'standard'),
  ('CIV3', 'CIV', 3, 'Ghislain Konan', false, 'standard'),
  ('CIV4', 'CIV', 4, 'Wilfried Singo', false, 'standard'),
  ('CIV5', 'CIV', 5, 'Odilon Kossounou', false, 'standard'),
  ('CIV6', 'CIV', 6, 'Evan Ndicka', false, 'standard'),
  ('CIV7', 'CIV', 7, 'Willy Boly', false, 'standard'),
  ('CIV8', 'CIV', 8, 'Emmanuel Agbadou', false, 'standard'),
  ('CIV9', 'CIV', 9, 'Ousmane Diomande', false, 'standard'),
  ('CIV10', 'CIV', 10, 'Franck Kessie', false, 'standard'),
  ('CIV11', 'CIV', 11, 'Seko Fofana', false, 'standard'),
  ('CIV12', 'CIV', 12, 'Ibrahim Sangare', false, 'standard'),
  ('CIV13', 'CIV', 13, 'Team Photo', false, 'standard'),
  ('CIV14', 'CIV', 14, 'Jean-Philippe', false, 'standard'),
  ('CIV15', 'CIV', 15, 'Amad Diallo', false, 'standard'),
  ('CIV16', 'CIV', 16, 'Sébastien Haller', false, 'standard'),
  ('CIV17', 'CIV', 17, 'Simon Adingra', false, 'standard'),
  ('CIV18', 'CIV', 18, 'Yan Diomande', false, 'standard'),
  ('CIV19', 'CIV', 19, 'Evann Guessand', false, 'standard'),
  ('CIV20', 'CIV', 20, 'Oumar Diakite', false, 'standard'),
  ('JPN1', 'JPN', 1, 'Team Logo', true, 'standard'),
  ('JPN2', 'JPN', 2, 'Zion Suzuki', false, 'standard'),
  ('JPN3', 'JPN', 3, 'Henry Heroki Mochizuki', false, 'standard'),
  ('JPN4', 'JPN', 4, 'Ayumu Seko', false, 'standard'),
  ('JPN5', 'JPN', 5, 'Junnosuke Suzuki', false, 'standard'),
  ('JPN6', 'JPN', 6, 'Shogo Taniguchi', false, 'standard'),
  ('JPN7', 'JPN', 7, 'Tsuyoshi Watanabe', false, 'standard'),
  ('JPN8', 'JPN', 8, 'Kaishu Sano', false, 'standard'),
  ('JPN9', 'JPN', 9, 'Yuki Soma', false, 'standard'),
  ('JPN10', 'JPN', 10, 'Ao Tanaka', false, 'standard'),
  ('JPN11', 'JPN', 11, 'Daichi Kamada', false, 'standard'),
  ('JPN12', 'JPN', 12, 'Takefusa Kubo', false, 'standard'),
  ('JPN13', 'JPN', 13, 'Team Photo', false, 'standard'),
  ('JPN14', 'JPN', 14, 'Ritsu Doan', false, 'standard'),
  ('JPN15', 'JPN', 15, 'Keito Nakamura', false, 'standard'),
  ('JPN16', 'JPN', 16, 'Takumi Minamino', false, 'standard'),
  ('JPN17', 'JPN', 17, 'Shuto Machino', false, 'standard'),
  ('JPN18', 'JPN', 18, 'Junya Ito', false, 'standard'),
  ('JPN19', 'JPN', 19, 'Koki Ogawa', false, 'standard'),
  ('JPN20', 'JPN', 20, 'Ayase Ueda', false, 'standard'),
  ('JOR1', 'JOR', 1, 'Team Logo', true, 'standard'),
  ('JOR2', 'JOR', 2, 'Yazeed Abulaila', false, 'standard'),
  ('JOR3', 'JOR', 3, 'Ihsan Haddad', false, 'standard'),
  ('JOR4', 'JOR', 4, 'Mohammad Abu Hashish', false, 'standard'),
  ('JOR5', 'JOR', 5, 'Yazan Al-Naimat', false, 'standard'),
  ('JOR6', 'JOR', 6, 'Abdallah Nasib', false, 'standard'),
  ('JOR7', 'JOR', 7, 'Saleem Obaid', false, 'standard'),
  ('JOR8', 'JOR', 8, 'Mohammad Abualnadi', false, 'standard'),
  ('JOR9', 'JOR', 9, 'Ibrahim Saadeh', false, 'standard'),
  ('JOR10', 'JOR', 10, 'Nizar Al-Rashdan', false, 'standard'),
  ('JOR11', 'JOR', 11, 'Noor Al-Rawabdeh', false, 'standard'),
  ('JOR12', 'JOR', 12, 'Mohannad Abu Taha', false, 'standard'),
  ('JOR13', 'JOR', 13, 'Team Photo', false, 'standard'),
  ('JOR14', 'JOR', 14, 'Amer Jamous', false, 'standard'),
  ('JOR15', 'JOR', 15, 'Musa Al-Tamari', false, 'standard'),
  ('JOR16', 'JOR', 16, 'Yazan Al-Arab', false, 'standard'),
  ('JOR17', 'JOR', 17, 'Mahmoud Al-Mardi', false, 'standard'),
  ('JOR18', 'JOR', 18, 'Ali Olwan', false, 'standard'),
  ('JOR19', 'JOR', 19, 'Mohammad Abu Zrayq', false, 'standard'),
  ('JOR20', 'JOR', 20, 'Ibrahim Sabra', false, 'standard'),
  ('MEX1', 'MEX', 1, 'Team Logo', true, 'standard'),
  ('MEX2', 'MEX', 2, 'Luis Malagón', false, 'standard'),
  ('MEX3', 'MEX', 3, 'Johan Vasquez', false, 'standard'),
  ('MEX4', 'MEX', 4, 'Jorge Sánchez', false, 'standard'),
  ('MEX5', 'MEX', 5, 'Cesar Montes', false, 'standard'),
  ('MEX6', 'MEX', 6, 'Jesus Gallardo', false, 'standard'),
  ('MEX7', 'MEX', 7, 'Israel Reyes', false, 'standard'),
  ('MEX8', 'MEX', 8, 'Diego Lainez', false, 'standard'),
  ('MEX9', 'MEX', 9, 'Carlos Rodriguez', false, 'standard'),
  ('MEX10', 'MEX', 10, 'Edson Alvarez', false, 'standard'),
  ('MEX11', 'MEX', 11, 'Orbelin Pineda', false, 'standard'),
  ('MEX12', 'MEX', 12, 'Marcel Ruiz', false, 'standard'),
  ('MEX13', 'MEX', 13, 'Team Photo', false, 'standard'),
  ('MEX14', 'MEX', 14, 'Érick Sánchez', false, 'standard'),
  ('MEX15', 'MEX', 15, 'Hirving Lozano', false, 'standard'),
  ('MEX16', 'MEX', 16, 'Santiago Giménez', false, 'standard'),
  ('MEX17', 'MEX', 17, 'Raúl Jiménez', false, 'standard'),
  ('MEX18', 'MEX', 18, 'Alexis Vega', false, 'standard'),
  ('MEX19', 'MEX', 19, 'Roberto Alvarado', false, 'standard'),
  ('MEX20', 'MEX', 20, 'Cesar Huerta', false, 'standard'),
  ('MAR1', 'MAR', 1, 'Team Logo', true, 'standard'),
  ('MAR2', 'MAR', 2, 'Yassine Bounou', false, 'standard'),
  ('MAR3', 'MAR', 3, 'Munir El Kajoui', false, 'standard'),
  ('MAR4', 'MAR', 4, 'Achraf Hakimi', false, 'standard'),
  ('MAR5', 'MAR', 5, 'Noussair Mazraoui', false, 'standard'),
  ('MAR6', 'MAR', 6, 'Nayef Aguerd', false, 'standard'),
  ('MAR7', 'MAR', 7, 'Roman Saiss', false, 'standard'),
  ('MAR8', 'MAR', 8, 'Jawad El Yamio', false, 'standard'),
  ('MAR9', 'MAR', 9, 'Adam Masina', false, 'standard'),
  ('MAR10', 'MAR', 10, 'Sofyan Amrabat', false, 'standard'),
  ('MAR11', 'MAR', 11, 'Azzedine Ounahi', false, 'standard'),
  ('MAR12', 'MAR', 12, 'Eliesse Ben Seghir', false, 'standard'),
  ('MAR13', 'MAR', 13, 'Team Photo', false, 'standard'),
  ('MAR14', 'MAR', 14, 'Bilal El Khannouss', false, 'standard'),
  ('MAR15', 'MAR', 15, 'Ismael Saibari', false, 'standard'),
  ('MAR16', 'MAR', 16, 'Youssef En-Nesyri', false, 'standard'),
  ('MAR17', 'MAR', 17, 'Abde Ezzalzouli', false, 'standard'),
  ('MAR18', 'MAR', 18, 'Soufiane Rahimi', false, 'standard'),
  ('MAR19', 'MAR', 19, 'Brahim Diaz', false, 'standard'),
  ('MAR20', 'MAR', 20, 'Ayoub El Kaabi', false, 'standard'),
  ('NED1', 'NED', 1, 'Team Logo', true, 'standard'),
  ('NED2', 'NED', 2, 'Bart Verbruggen', false, 'standard'),
  ('NED3', 'NED', 3, 'Virgil van Dijk', false, 'standard'),
  ('NED4', 'NED', 4, 'Micky van de Ven', false, 'standard'),
  ('NED5', 'NED', 5, 'Jurrien Timber', false, 'standard'),
  ('NED6', 'NED', 6, 'Denzel Dumfries', false, 'standard'),
  ('NED7', 'NED', 7, 'Nathan Aké', false, 'standard'),
  ('NED8', 'NED', 8, 'Jeremie Frimpong', false, 'standard'),
  ('NED9', 'NED', 9, 'Jan Paul van Hecke', false, 'standard'),
  ('NED10', 'NED', 10, 'Tijjani Reijnders', false, 'standard'),
  ('NED11', 'NED', 11, 'Ryan Gravenberch', false, 'standard'),
  ('NED12', 'NED', 12, 'Teun Koopmeiners', false, 'standard'),
  ('NED13', 'NED', 13, 'Team Photo', false, 'standard'),
  ('NED14', 'NED', 14, 'Frenkie de Jong', false, 'standard'),
  ('NED15', 'NED', 15, 'Xavi Simons', false, 'standard'),
  ('NED16', 'NED', 16, 'Justin Kluivert', false, 'standard'),
  ('NED17', 'NED', 17, 'Memphis Depay', false, 'standard'),
  ('NED18', 'NED', 18, 'Donyell Malen', false, 'standard'),
  ('NED19', 'NED', 19, 'Wout Weghorst', false, 'standard'),
  ('NED20', 'NED', 20, 'Cody Gakpo', false, 'standard'),
  ('NZL1', 'NZL', 1, 'Team Logo', true, 'standard'),
  ('NZL2', 'NZL', 2, 'Max Crocombe Payne', false, 'standard'),
  ('NZL3', 'NZL', 3, 'Alex Paulsen', false, 'standard'),
  ('NZL4', 'NZL', 4, 'Michael Boxall', false, 'standard'),
  ('NZL5', 'NZL', 5, 'Liberato Cacace', false, 'standard'),
  ('NZL6', 'NZL', 6, 'Tim Payne', false, 'standard'),
  ('NZL7', 'NZL', 7, 'Tyler Bindon', false, 'standard'),
  ('NZL8', 'NZL', 8, 'Francis de Vries', false, 'standard'),
  ('NZL9', 'NZL', 9, 'Finn Surman', false, 'standard'),
  ('NZL10', 'NZL', 10, 'Joe Bell', false, 'standard'),
  ('NZL11', 'NZL', 11, 'Sarpreet Singh', false, 'standard'),
  ('NZL12', 'NZL', 12, 'Ryan Thomas', false, 'standard'),
  ('NZL13', 'NZL', 13, 'Team Photo', false, 'standard'),
  ('NZL14', 'NZL', 14, 'Matthew Garbett', false, 'standard'),
  ('NZL15', 'NZL', 15, 'Marko Stamenić', false, 'standard'),
  ('NZL16', 'NZL', 16, 'Ben Old', false, 'standard'),
  ('NZL17', 'NZL', 17, 'Chris Wood', false, 'standard'),
  ('NZL18', 'NZL', 18, 'Elijah Just', false, 'standard'),
  ('NZL19', 'NZL', 19, 'Callum McCowatt', false, 'standard'),
  ('NZL20', 'NZL', 20, 'Kosta Barbarouses', false, 'standard'),
  ('NOR1', 'NOR', 1, 'Team Logo', true, 'standard'),
  ('NOR2', 'NOR', 2, 'Orjan Nyland', false, 'standard'),
  ('NOR3', 'NOR', 3, 'Julian Ryerson', false, 'standard'),
  ('NOR4', 'NOR', 4, 'Leo Østigård', false, 'standard'),
  ('NOR5', 'NOR', 5, 'Kristoffer Ajer', false, 'standard'),
  ('NOR6', 'NOR', 6, 'Marcus Holmgren Pedersen', false, 'standard'),
  ('NOR7', 'NOR', 7, 'David Møller Wolfe', false, 'standard'),
  ('NOR8', 'NOR', 8, 'Torbjørn Heggem', false, 'standard'),
  ('NOR9', 'NOR', 9, 'Morten Thorsby', false, 'standard'),
  ('NOR10', 'NOR', 10, 'Martin Ødegaard', false, 'standard'),
  ('NOR11', 'NOR', 11, 'Sander Berge', false, 'standard'),
  ('NOR12', 'NOR', 12, 'Andreas Schjelderup', false, 'standard'),
  ('NOR13', 'NOR', 13, 'Team Photo', false, 'standard'),
  ('NOR14', 'NOR', 14, 'Patrick Berg', false, 'standard'),
  ('NOR15', 'NOR', 15, 'Erling Haaland', false, 'standard'),
  ('NOR16', 'NOR', 16, 'Alexander Sørloth', false, 'standard'),
  ('NOR17', 'NOR', 17, 'Aron Dønnum', false, 'standard'),
  ('NOR18', 'NOR', 18, 'Jorgen Strand Larsen', false, 'standard'),
  ('NOR19', 'NOR', 19, 'Antonio Nusa', false, 'standard'),
  ('NOR20', 'NOR', 20, 'Oscar Bobb', false, 'standard'),
  ('PAN1', 'PAN', 1, 'Team Logo', true, 'standard'),
  ('PAN2', 'PAN', 2, 'Orlando Mosquera', false, 'standard'),
  ('PAN3', 'PAN', 3, 'Luis Mejia', false, 'standard'),
  ('PAN4', 'PAN', 4, 'Fidel Escobar', false, 'standard'),
  ('PAN5', 'PAN', 5, 'Andres Andrade', false, 'standard'),
  ('PAN6', 'PAN', 6, 'Michael Amir Murillo', false, 'standard'),
  ('PAN7', 'PAN', 7, 'Eric Davis', false, 'standard'),
  ('PAN8', 'PAN', 8, 'Jose Cordoba', false, 'standard'),
  ('PAN9', 'PAN', 9, 'Cesar Blackman', false, 'standard'),
  ('PAN10', 'PAN', 10, 'Cristian Martinez', false, 'standard'),
  ('PAN11', 'PAN', 11, 'Aníbal Godoy', false, 'standard'),
  ('PAN12', 'PAN', 12, 'Adalberto Carrasquilla', false, 'standard'),
  ('PAN13', 'PAN', 13, 'Team Photo', false, 'standard'),
  ('PAN14', 'PAN', 14, 'Édgar Bárcenas', false, 'standard'),
  ('PAN15', 'PAN', 15, 'Carlos Harvey', false, 'standard'),
  ('PAN16', 'PAN', 16, 'Ismael Díaz', false, 'standard'),
  ('PAN17', 'PAN', 17, 'Jose Fajardo', false, 'standard'),
  ('PAN18', 'PAN', 18, 'Cecilio Waterman', false, 'standard'),
  ('PAN19', 'PAN', 19, 'Jose Luiz Rodriguez', false, 'standard'),
  ('PAN20', 'PAN', 20, 'Alberto Quintero', false, 'standard'),
  ('PAR1', 'PAR', 1, 'Team Logo', true, 'standard'),
  ('PAR2', 'PAR', 2, 'Roberto Fernandez', false, 'standard'),
  ('PAR3', 'PAR', 3, 'Orlando Gill', false, 'standard'),
  ('PAR4', 'PAR', 4, 'Gustavo Gomez', false, 'standard'),
  ('PAR5', 'PAR', 5, 'Fabián Balbuena', false, 'standard'),
  ('PAR6', 'PAR', 6, 'Juan José Cáceres', false, 'standard'),
  ('PAR7', 'PAR', 7, 'Omar Alderete', false, 'standard'),
  ('PAR8', 'PAR', 8, 'Junior Alonso', false, 'standard'),
  ('PAR9', 'PAR', 9, 'Mathías Villasanti', false, 'standard'),
  ('PAR10', 'PAR', 10, 'Diego Gomez', false, 'standard'),
  ('PAR11', 'PAR', 11, 'Damián Bobadilla', false, 'standard'),
  ('PAR12', 'PAR', 12, 'Andres Cubas', false, 'standard'),
  ('PAR13', 'PAR', 13, 'Team Photo', false, 'standard'),
  ('PAR14', 'PAR', 14, 'Matias Galarza Fonda', false, 'standard'),
  ('PAR15', 'PAR', 15, 'Julio Enciso', false, 'standard'),
  ('PAR16', 'PAR', 16, 'Alejandro Romero Gamarra', false, 'standard'),
  ('PAR17', 'PAR', 17, 'Miguel Almirón', false, 'standard'),
  ('PAR18', 'PAR', 18, 'Ramon Sosa', false, 'standard'),
  ('PAR19', 'PAR', 19, 'Angel Romero', false, 'standard'),
  ('PAR20', 'PAR', 20, 'Antonio Sanabria', false, 'standard'),
  ('POR1', 'POR', 1, 'Team Logo', true, 'standard'),
  ('POR2', 'POR', 2, 'Diogo Costa', false, 'standard'),
  ('POR3', 'POR', 3, 'Jose Sa', false, 'standard'),
  ('POR4', 'POR', 4, 'Ruben Dias', false, 'standard'),
  ('POR5', 'POR', 5, 'João Cancelo', false, 'standard'),
  ('POR6', 'POR', 6, 'Diogo Dalot', false, 'standard'),
  ('POR7', 'POR', 7, 'Nuno Mendes', false, 'standard'),
  ('POR8', 'POR', 8, 'Gonçalo Inácio', false, 'standard'),
  ('POR9', 'POR', 9, 'Bernardo Silva', false, 'standard'),
  ('POR10', 'POR', 10, 'Bruno Fernandes', false, 'standard'),
  ('POR11', 'POR', 11, 'Ruben Neves', false, 'standard'),
  ('POR12', 'POR', 12, 'Vitinha', false, 'standard'),
  ('POR13', 'POR', 13, 'Team Photo', false, 'standard'),
  ('POR14', 'POR', 14, 'João Neves', false, 'standard'),
  ('POR15', 'POR', 15, 'Cristiano Ronaldo', false, 'standard'),
  ('POR16', 'POR', 16, 'Francisco Trincao', false, 'standard'),
  ('POR17', 'POR', 17, 'João Felix', false, 'standard'),
  ('POR18', 'POR', 18, 'Gonçalo Ramos', false, 'standard'),
  ('POR19', 'POR', 19, 'Pedro Neto', false, 'standard'),
  ('POR20', 'POR', 20, 'Rafael Leão', false, 'standard'),
  ('QAT1', 'QAT', 1, 'Team Logo', true, 'standard'),
  ('QAT2', 'QAT', 2, 'Meshaal Barsham', false, 'standard'),
  ('QAT3', 'QAT', 3, 'Sultan Albrake', false, 'standard'),
  ('QAT4', 'QAT', 4, 'Lucas Mendes', false, 'standard'),
  ('QAT5', 'QAT', 5, 'Homam Ahmed', false, 'standard'),
  ('QAT6', 'QAT', 6, 'Boualem Khoukhi', false, 'standard'),
  ('QAT7', 'QAT', 7, 'Pedro Miguel', false, 'standard'),
  ('QAT8', 'QAT', 8, 'Tarek Salman', false, 'standard'),
  ('QAT9', 'QAT', 9, 'Mohamed Al-Wahdani', false, 'standard'),
  ('QAT10', 'QAT', 10, 'Karim Boudiaf', false, 'standard'),
  ('QAT11', 'QAT', 11, 'Assim Madibo', false, 'standard'),
  ('QAT12', 'QAT', 12, 'Ahmed Fatehi', false, 'standard'),
  ('QAT13', 'QAT', 13, 'Team Photo', false, 'standard'),
  ('QAT14', 'QAT', 14, 'Mohammed Waad', false, 'standard'),
  ('QAT15', 'QAT', 15, 'Abdulaziz Hatem', false, 'standard'),
  ('QAT16', 'QAT', 16, 'Hassan Al-Haydos', false, 'standard'),
  ('QAT17', 'QAT', 17, 'Edmilson Junior', false, 'standard'),
  ('QAT18', 'QAT', 18, 'Akram Hassan Afif', false, 'standard'),
  ('QAT19', 'QAT', 19, 'Ahmed Al Ganehi', false, 'standard'),
  ('QAT20', 'QAT', 20, 'Almoez Ali', false, 'standard'),
  ('KSA1', 'KSA', 1, 'Team Logo', true, 'standard'),
  ('KSA2', 'KSA', 2, 'Nawaf Alaqidi', false, 'standard'),
  ('KSA3', 'KSA', 3, 'Abdulrahman Al-Aboud', false, 'standard'),
  ('KSA4', 'KSA', 4, 'Saud Abdulhamid', false, 'standard'),
  ('KSA5', 'KSA', 5, 'Nawaf Bouwashl', false, 'standard'),
  ('KSA6', 'KSA', 6, 'Jihad Thakri', false, 'standard'),
  ('KSA7', 'KSA', 7, 'Moteb Al-Harbi', false, 'standard'),
  ('KSA8', 'KSA', 8, 'Hassan Altambakti', false, 'standard'),
  ('KSA9', 'KSA', 9, 'Musab Aljuwayr', false, 'standard'),
  ('KSA10', 'KSA', 10, 'Ziyad Aljohani', false, 'standard'),
  ('KSA11', 'KSA', 11, 'Abdullah Alkhaibari', false, 'standard'),
  ('KSA12', 'KSA', 12, 'Nasser Aldawsari', false, 'standard'),
  ('KSA13', 'KSA', 13, 'Team Photo', false, 'standard'),
  ('KSA14', 'KSA', 14, 'Saleh Abu Alshamat', false, 'standard'),
  ('KSA15', 'KSA', 15, 'Marwan Alsahafi', false, 'standard'),
  ('KSA16', 'KSA', 16, 'Salem Aldawsari', false, 'standard'),
  ('KSA17', 'KSA', 17, 'Abdulrahman Al-Qahtani', false, 'standard'),
  ('KSA18', 'KSA', 18, 'Feras Akbrikan', false, 'standard'),
  ('KSA19', 'KSA', 19, 'Saleh Alshehri', false, 'standard'),
  ('KSA20', 'KSA', 20, 'Abdullah Al-Khaibari', false, 'standard'),
  ('SCO1', 'SCO', 1, 'Team Logo', true, 'standard'),
  ('SCO2', 'SCO', 2, 'Angus Gunn', false, 'standard'),
  ('SCO3', 'SCO', 3, 'Jack Hendry', false, 'standard'),
  ('SCO4', 'SCO', 4, 'Kieran Tierney', false, 'standard'),
  ('SCO5', 'SCO', 5, 'Aaron Hickey', false, 'standard'),
  ('SCO6', 'SCO', 6, 'Andrew Robertson', false, 'standard'),
  ('SCO7', 'SCO', 7, 'Scott McKenna', false, 'standard'),
  ('SCO8', 'SCO', 8, 'John Souttar', false, 'standard'),
  ('SCO9', 'SCO', 9, 'Anthony Ralston', false, 'standard'),
  ('SCO10', 'SCO', 10, 'Grant Hanley', false, 'standard'),
  ('SCO11', 'SCO', 11, 'Scott McTominay', false, 'standard'),
  ('SCO12', 'SCO', 12, 'Billy Gilmour', false, 'standard'),
  ('SCO13', 'SCO', 13, 'Team Photo', false, 'standard'),
  ('SCO14', 'SCO', 14, 'Lewis Ferguson', false, 'standard'),
  ('SCO15', 'SCO', 15, 'Ryan Christie', false, 'standard'),
  ('SCO16', 'SCO', 16, 'Kenny McLean', false, 'standard'),
  ('SCO17', 'SCO', 17, 'John McGinn', false, 'standard'),
  ('SCO18', 'SCO', 18, 'Lyndon Dykes', false, 'standard'),
  ('SCO19', 'SCO', 19, 'Che Adams', false, 'standard'),
  ('SCO20', 'SCO', 20, 'Ben Gannon', false, 'standard'),
  ('SEN1', 'SEN', 1, 'Team Logo', true, 'standard'),
  ('SEN2', 'SEN', 2, 'Edouard Mendy', false, 'standard'),
  ('SEN3', 'SEN', 3, 'Yehvann Diouf', false, 'standard'),
  ('SEN4', 'SEN', 4, 'Moussa Niakhaté', false, 'standard'),
  ('SEN5', 'SEN', 5, 'Abdoulaye Seck', false, 'standard'),
  ('SEN6', 'SEN', 6, 'Ismail Jakobs', false, 'standard'),
  ('SEN7', 'SEN', 7, 'El Hadji Malick Diouf', false, 'standard'),
  ('SEN8', 'SEN', 8, 'Kalidou Koulibaly', false, 'standard'),
  ('SEN9', 'SEN', 9, 'Idrissa Gana Gueye', false, 'standard'),
  ('SEN10', 'SEN', 10, 'Pape Matar Sarr', false, 'standard'),
  ('SEN11', 'SEN', 11, 'Pape Gueye', false, 'standard'),
  ('SEN12', 'SEN', 12, 'Habib Diarra', false, 'standard'),
  ('SEN13', 'SEN', 13, 'Team Photo', false, 'standard'),
  ('SEN14', 'SEN', 14, 'Lamine Camara', false, 'standard'),
  ('SEN15', 'SEN', 15, 'Sadio Mane', false, 'standard'),
  ('SEN16', 'SEN', 16, 'Ismaïla Sarr', false, 'standard'),
  ('SEN17', 'SEN', 17, 'Boulaye Dia', false, 'standard'),
  ('SEN18', 'SEN', 18, 'Iliman Ndiaye', false, 'standard'),
  ('SEN19', 'SEN', 19, 'Nicolas Jackson', false, 'standard'),
  ('SEN20', 'SEN', 20, 'Krepin Diatta', false, 'standard'),
  ('RSA1', 'RSA', 1, 'Team Logo', true, 'standard'),
  ('RSA2', 'RSA', 2, 'Ronwen Williams', false, 'standard'),
  ('RSA3', 'RSA', 3, 'Sipho Chaine', false, 'standard'),
  ('RSA4', 'RSA', 4, 'Aubrey Modiba', false, 'standard'),
  ('RSA5', 'RSA', 5, 'Samukele Kabini', false, 'standard'),
  ('RSA6', 'RSA', 6, 'Mbekezeli Mbokazi', false, 'standard'),
  ('RSA7', 'RSA', 7, 'Khulumani Ndamane', false, 'standard'),
  ('RSA8', 'RSA', 8, 'Siyabonga Ngezana', false, 'standard'),
  ('RSA9', 'RSA', 9, 'Khuliso Mudau', false, 'standard'),
  ('RSA10', 'RSA', 10, 'Nkosinathi Sibisi', false, 'standard'),
  ('RSA11', 'RSA', 11, 'Teboho Mokoena', false, 'standard'),
  ('RSA12', 'RSA', 12, 'Thalente Mbatha', false, 'standard'),
  ('RSA13', 'RSA', 13, 'Team Photo', false, 'standard'),
  ('RSA14', 'RSA', 14, 'Bathasi Aubaas', false, 'standard'),
  ('RSA15', 'RSA', 15, 'Yaya Sithole', false, 'standard'),
  ('RSA16', 'RSA', 16, 'Sipho Mbule', false, 'standard'),
  ('RSA17', 'RSA', 17, 'Lyle Foster', false, 'standard'),
  ('RSA18', 'RSA', 18, 'Iqraam Rayners', false, 'standard'),
  ('RSA19', 'RSA', 19, 'Mohau Nkota', false, 'standard'),
  ('RSA20', 'RSA', 20, 'Oswin Appollis', false, 'standard'),
  ('KOR1', 'KOR', 1, 'Team Logo', true, 'standard'),
  ('KOR2', 'KOR', 2, 'Kim Seung-gyu', false, 'standard'),
  ('KOR3', 'KOR', 3, 'Lee Seung-mo', false, 'standard'),
  ('KOR4', 'KOR', 4, 'Kim Min-jae', false, 'standard'),
  ('KOR5', 'KOR', 5, 'Yu Hyun-su', false, 'standard'),
  ('KOR6', 'KOR', 6, 'Lee Young-jae', false, 'standard'),
  ('KOR7', 'KOR', 7, 'Kim Jin-su', false, 'standard'),
  ('KOR8', 'KOR', 8, 'Kim Tae-hwan', false, 'standard'),
  ('KOR9', 'KOR', 9, 'Hwang In-beom', false, 'standard'),
  ('KOR10', 'KOR', 10, 'Jung Woo-young', false, 'standard'),
  ('KOR11', 'KOR', 11, 'Lee Kang-in', false, 'standard'),
  ('KOR12', 'KOR', 12, 'Kwon Kyung-won', false, 'standard'),
  ('KOR13', 'KOR', 13, 'Team Photo', false, 'standard'),
  ('KOR14', 'KOR', 14, 'Seol Young-woo', false, 'standard'),
  ('KOR15', 'KOR', 15, 'Jens Castrop', false, 'standard'),
  ('KOR16', 'KOR', 16, 'Oh Hyeon-gyu', false, 'standard'),
  ('KOR17', 'KOR', 17, 'Cho Gue-sung', false, 'standard'),
  ('KOR18', 'KOR', 18, 'Son Heung-min', false, 'standard'),
  ('KOR19', 'KOR', 19, 'Hwang Hee-chan', false, 'standard'),
  ('KOR20', 'KOR', 20, 'Hwang Ui-jo', false, 'standard'),
  ('ESP1', 'ESP', 1, 'Team Logo', true, 'standard'),
  ('ESP2', 'ESP', 2, 'Unai Simon', false, 'standard'),
  ('ESP3', 'ESP', 3, 'Robin Le Normand', false, 'standard'),
  ('ESP4', 'ESP', 4, 'Aymeric Laporte', false, 'standard'),
  ('ESP5', 'ESP', 5, 'Dean Huijsen', false, 'standard'),
  ('ESP6', 'ESP', 6, 'Pedro Porro', false, 'standard'),
  ('ESP7', 'ESP', 7, 'Dani Carvajal', false, 'standard'),
  ('ESP8', 'ESP', 8, 'Marc Cucurella', false, 'standard'),
  ('ESP9', 'ESP', 9, 'Martín Zubimendi', false, 'standard'),
  ('ESP10', 'ESP', 10, 'Rodri', false, 'standard'),
  ('ESP11', 'ESP', 11, 'Pedri', false, 'standard'),
  ('ESP12', 'ESP', 12, 'Fabian Ruiz', false, 'standard'),
  ('ESP13', 'ESP', 13, 'Team Photo', false, 'standard'),
  ('ESP14', 'ESP', 14, 'Mikel Merino', false, 'standard'),
  ('ESP15', 'ESP', 15, 'Lamine Yamal', false, 'standard'),
  ('ESP16', 'ESP', 16, 'Dani Olmo', false, 'standard'),
  ('ESP17', 'ESP', 17, 'Nico Williams', false, 'standard'),
  ('ESP18', 'ESP', 18, 'Ferran Torres', false, 'standard'),
  ('ESP19', 'ESP', 19, 'Álvaro Morata', false, 'standard'),
  ('ESP20', 'ESP', 20, 'Mikel Oyarzabal', false, 'standard'),
  ('SWE1', 'SWE', 1, 'Team Logo', true, 'standard'),
  ('SWE2', 'SWE', 2, 'Victor Johansson', false, 'standard'),
  ('SWE3', 'SWE', 3, 'Isak Hien', false, 'standard'),
  ('SWE4', 'SWE', 4, 'Gabriel Gudmundsson', false, 'standard'),
  ('SWE5', 'SWE', 5, 'Emil Holm', false, 'standard'),
  ('SWE6', 'SWE', 6, 'Victor Nilsson Lindelöf', false, 'standard'),
  ('SWE7', 'SWE', 7, 'Gustaf Lagerbielke', false, 'standard'),
  ('SWE8', 'SWE', 8, 'Lucas Bergvall', false, 'standard'),
  ('SWE9', 'SWE', 9, 'Hugo Larsson', false, 'standard'),
  ('SWE10', 'SWE', 10, 'Jesper Karlström', false, 'standard'),
  ('SWE11', 'SWE', 11, 'Yasin Ayari', false, 'standard'),
  ('SWE12', 'SWE', 12, 'Mattias Svanberg', false, 'standard'),
  ('SWE13', 'SWE', 13, 'Team Photo', false, 'standard'),
  ('SWE14', 'SWE', 14, 'Daniel Svensson', false, 'standard'),
  ('SWE15', 'SWE', 15, 'Ken Sema', false, 'standard'),
  ('SWE16', 'SWE', 16, 'Roony Bardghji', false, 'standard'),
  ('SWE17', 'SWE', 17, 'Dejan Kulusevski', false, 'standard'),
  ('SWE18', 'SWE', 18, 'Anthony Elanga', false, 'standard'),
  ('SWE19', 'SWE', 19, 'Alexander Isak', false, 'standard'),
  ('SWE20', 'SWE', 20, 'Viktor Gyökeres', false, 'standard'),
  ('SUI1', 'SUI', 1, 'Team Logo', true, 'standard'),
  ('SUI2', 'SUI', 2, 'Gregor Kobel', false, 'standard'),
  ('SUI3', 'SUI', 3, 'Yvon Mvogo', false, 'standard'),
  ('SUI4', 'SUI', 4, 'Manuel Akanji', false, 'standard'),
  ('SUI5', 'SUI', 5, 'Ricardo Rodriguez', false, 'standard'),
  ('SUI6', 'SUI', 6, 'Nico Elvedi', false, 'standard'),
  ('SUI7', 'SUI', 7, 'Aurèle Amenda', false, 'standard'),
  ('SUI8', 'SUI', 8, 'Silvan Widmer', false, 'standard'),
  ('SUI9', 'SUI', 9, 'Granit Xhaka', false, 'standard'),
  ('SUI10', 'SUI', 10, 'Denis Zakaria', false, 'standard'),
  ('SUI11', 'SUI', 11, 'Remo Freuler', false, 'standard'),
  ('SUI12', 'SUI', 12, 'Fabian Rieder', false, 'standard'),
  ('SUI13', 'SUI', 13, 'Team Photo', false, 'standard'),
  ('SUI14', 'SUI', 14, 'Ardon Jashari', false, 'standard'),
  ('SUI15', 'SUI', 15, 'Johan Manzambi', false, 'standard'),
  ('SUI16', 'SUI', 16, 'Michel Aebischer', false, 'standard'),
  ('SUI17', 'SUI', 17, 'Breel Embolo', false, 'standard'),
  ('SUI18', 'SUI', 18, 'Ruben Vargas', false, 'standard'),
  ('SUI19', 'SUI', 19, 'Dan Ndoye', false, 'standard'),
  ('SUI20', 'SUI', 20, 'Zeki Amdouni', false, 'standard'),
  ('TUN1', 'TUN', 1, 'Team Logo', true, 'standard'),
  ('TUN2', 'TUN', 2, 'Bechir Ben Said', false, 'standard'),
  ('TUN3', 'TUN', 3, 'Aymen Dahmen', false, 'standard'),
  ('TUN4', 'TUN', 4, 'Yan Valery', false, 'standard'),
  ('TUN5', 'TUN', 5, 'Montassar Talbi', false, 'standard'),
  ('TUN6', 'TUN', 6, 'Yassine Meriah', false, 'standard'),
  ('TUN7', 'TUN', 7, 'Ali Abdi', false, 'standard'),
  ('TUN8', 'TUN', 8, 'Dylan Bronn', false, 'standard'),
  ('TUN9', 'TUN', 9, 'Ellyes Skhiri', false, 'standard'),
  ('TUN10', 'TUN', 10, 'Aissa Laidouni', false, 'standard'),
  ('TUN11', 'TUN', 11, 'Ferjani Sassi', false, 'standard'),
  ('TUN12', 'TUN', 12, 'Mohamed Ali Ben Romdhane', false, 'standard'),
  ('TUN13', 'TUN', 13, 'Team Photo', false, 'standard'),
  ('TUN14', 'TUN', 14, 'Hannibal Mejbri', false, 'standard'),
  ('TUN15', 'TUN', 15, 'Elias Achouri', false, 'standard'),
  ('TUN16', 'TUN', 16, 'Elias Saad', false, 'standard'),
  ('TUN17', 'TUN', 17, 'Hazem Mastouri', false, 'standard'),
  ('TUN18', 'TUN', 18, 'Ismael Gharbi', false, 'standard'),
  ('TUN19', 'TUN', 19, 'Sayfallah Ltaief', false, 'standard'),
  ('TUN20', 'TUN', 20, 'Naim Sliti', false, 'standard'),
  ('TUR1', 'TUR', 1, 'Team Logo', true, 'standard'),
  ('TUR2', 'TUR', 2, 'Ugurcan Cakir', false, 'standard'),
  ('TUR3', 'TUR', 3, 'Mert Muldur', false, 'standard'),
  ('TUR4', 'TUR', 4, 'Zeki Celik', false, 'standard'),
  ('TUR5', 'TUR', 5, 'Abdulkerim Bardakci', false, 'standard'),
  ('TUR6', 'TUR', 6, 'Caglar Soyuncu', false, 'standard'),
  ('TUR7', 'TUR', 7, 'Merih Demiral', false, 'standard'),
  ('TUR8', 'TUR', 8, 'Ferdi Kadioglu', false, 'standard'),
  ('TUR9', 'TUR', 9, 'Kaan Ayhan', false, 'standard'),
  ('TUR10', 'TUR', 10, 'Ismail Yuksek', false, 'standard'),
  ('TUR11', 'TUR', 11, 'Hakan Calhanoglu', false, 'standard'),
  ('TUR12', 'TUR', 12, 'Orkun Kokcu', false, 'standard'),
  ('TUR13', 'TUR', 13, 'Team Photo', false, 'standard'),
  ('TUR14', 'TUR', 14, 'Arda Guler', false, 'standard'),
  ('TUR15', 'TUR', 15, 'Irfan Can Kahveci', false, 'standard'),
  ('TUR16', 'TUR', 16, 'Yunus Akgun', false, 'standard'),
  ('TUR17', 'TUR', 17, 'Can Uzun', false, 'standard'),
  ('TUR18', 'TUR', 18, 'Baris Alper Yilmaz', false, 'standard'),
  ('TUR19', 'TUR', 19, 'Kerem Akturkoglu', false, 'standard'),
  ('TUR20', 'TUR', 20, 'Kenan Yildiz', false, 'standard'),
  ('URU1', 'URU', 1, 'Team Logo', true, 'standard'),
  ('URU2', 'URU', 2, 'Sergio Rochet', false, 'standard'),
  ('URU3', 'URU', 3, 'Santiago Mele', false, 'standard'),
  ('URU4', 'URU', 4, 'Ronald Araujo', false, 'standard'),
  ('URU5', 'URU', 5, 'José María Giménez', false, 'standard'),
  ('URU6', 'URU', 6, 'Sebastian Caceres', false, 'standard'),
  ('URU7', 'URU', 7, 'Mathias Olivera', false, 'standard'),
  ('URU8', 'URU', 8, 'Guillermo Varela', false, 'standard'),
  ('URU9', 'URU', 9, 'Nahitan Nandez', false, 'standard'),
  ('URU10', 'URU', 10, 'Federico Valverde', false, 'standard'),
  ('URU11', 'URU', 11, 'Giorgian De Arrascaeta', false, 'standard'),
  ('URU12', 'URU', 12, 'Rodrigo Bentancur', false, 'standard'),
  ('URU13', 'URU', 13, 'Team Photo', false, 'standard'),
  ('URU14', 'URU', 14, 'Manuel Ugarte', false, 'standard'),
  ('URU15', 'URU', 15, 'Nicolás de la Cruz', false, 'standard'),
  ('URU16', 'URU', 16, 'Maxi Araujo', false, 'standard'),
  ('URU17', 'URU', 17, 'Darwin Núñez', false, 'standard'),
  ('URU18', 'URU', 18, 'Federico Viñas', false, 'standard'),
  ('URU19', 'URU', 19, 'Rodrigo Aguirre', false, 'standard'),
  ('URU20', 'URU', 20, 'Facundo Pellistri', false, 'standard'),
  ('USA1', 'USA', 1, 'Team Logo', true, 'standard'),
  ('USA2', 'USA', 2, 'Matt Freese', false, 'standard'),
  ('USA3', 'USA', 3, 'Chris Richards', false, 'standard'),
  ('USA4', 'USA', 4, 'Tim Ream', false, 'standard'),
  ('USA5', 'USA', 5, 'Mark McKenzie', false, 'standard'),
  ('USA6', 'USA', 6, 'Alex Freeman', false, 'standard'),
  ('USA7', 'USA', 7, 'Antonee Robinson', false, 'standard'),
  ('USA8', 'USA', 8, 'Tyler Adams', false, 'standard'),
  ('USA9', 'USA', 9, 'Tanner Tessmann', false, 'standard'),
  ('USA10', 'USA', 10, 'Weston McKennie', false, 'standard'),
  ('USA11', 'USA', 11, 'Christian Roldan', false, 'standard'),
  ('USA12', 'USA', 12, 'Timothy Weah', false, 'standard'),
  ('USA13', 'USA', 13, 'Team Photo', false, 'standard'),
  ('USA14', 'USA', 14, 'Diego Luna', false, 'standard'),
  ('USA15', 'USA', 15, 'Malik Tillman', false, 'standard'),
  ('USA16', 'USA', 16, 'Christian Pulisic', false, 'standard'),
  ('USA17', 'USA', 17, 'Brenden Aaronson', false, 'standard'),
  ('USA18', 'USA', 18, 'Ricardo Pepi', false, 'standard'),
  ('USA19', 'USA', 19, 'Haji Wright', false, 'standard'),
  ('USA20', 'USA', 20, 'Folarin Balogun', false, 'standard'),
  ('UZB1', 'UZB', 1, 'Team Logo', true, 'standard'),
  ('UZB2', 'UZB', 2, 'Utkir Yusupov', false, 'standard'),
  ('UZB3', 'UZB', 3, 'Farrukh Savfiev', false, 'standard'),
  ('UZB4', 'UZB', 4, 'Sherzod Nasrullaev', false, 'standard'),
  ('UZB5', 'UZB', 5, 'Umar Eshmurodov', false, 'standard'),
  ('UZB6', 'UZB', 6, 'Husniddin Aliqulov', false, 'standard'),
  ('UZB7', 'UZB', 7, 'Rustamjon Ashurmatov', false, 'standard'),
  ('UZB8', 'UZB', 8, 'Khojiakbar Alijonov', false, 'standard'),
  ('UZB9', 'UZB', 9, 'Abdukodir Khusanov', false, 'standard'),
  ('UZB10', 'UZB', 10, 'Odiljon Hamrobekov', false, 'standard'),
  ('UZB11', 'UZB', 11, 'Otabek Shukurov', false, 'standard'),
  ('UZB12', 'UZB', 12, 'Jamshid Iskanderov', false, 'standard'),
  ('UZB13', 'UZB', 13, 'Team Photo', false, 'standard'),
  ('UZB14', 'UZB', 14, 'Azizbek Turgunboev', false, 'standard'),
  ('UZB15', 'UZB', 15, 'Khojimat Erkinov', false, 'standard'),
  ('UZB16', 'UZB', 16, 'Eldor Shomurodov', false, 'standard'),
  ('UZB17', 'UZB', 17, 'Oston Urunov', false, 'standard'),
  ('UZB18', 'UZB', 18, 'Jaloliddin Masharipov', false, 'standard'),
  ('UZB19', 'UZB', 19, 'Igor Sergeev', false, 'standard'),
  ('UZB20', 'UZB', 20, 'Abbosbek Fayzullaev', false, 'standard');